[package]
name = "floe-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "floe"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
floe-core = { path = "../floe-core" }
