[package]
name = "floe-core"
version = "0.1.6"
edition = "2021"
description = "Core library for Floe, a YAML-driven technical ingestion tool."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/malon64/floe"
homepage = "https://github.com/malon64/floe"
keywords = ["ingestion", "data-quality", "csv", "polars", "yaml"]

[lib]
path = "src/lib.rs"

[dependencies]
yaml-rust2 = "0.11"
polars = { version = "0.52.0", features = ["csv", "parquet", "lazy", "timezones", "dtype-date", "dtype-datetime", "dtype-time", "polars-ops", "is_unique", "is_first_distinct"] }
deltalake = { version = "0.30.1", features = ["datafusion", "s3", "azure"] }
url = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = { version = "0.3", features = ["formatting"] }
glob = "0.3"
aws-config = "1"
aws-sdk-s3 = "1"
google-cloud-storage = { package = "gcloud-storage", version = "1.2.0" }
tempfile = "3"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "fs", "io-util"] }
azure_core = "0.20"
azure_identity = "0.20"
azure_storage = "0.20"
azure_storage_blobs = "0.20"
futures = "0.3"
