[package]
name = "floe-core"
version = "0.1.2"
edition = "2021"
description = "Core library for Floe, a YAML-driven technical ingestion tool."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/malon64/floe"
homepage = "https://github.com/malon64/floe"
keywords = ["ingestion", "data-quality", "csv", "polars", "yaml"]

[lib]
path = "src/lib.rs"

[dependencies]
yaml-rust2 = "0.11"
polars = { version = "0.52.0", features = ["csv", "parquet", "lazy", "timezones"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = { version = "0.3", features = ["formatting"] }
